locallibrary/catalog/urls.py
from django.urls import path, re_path
from .views import index, BooksListView, BookDetailView, AuthorsListView, AuthorDetailView, AuthorCreateView, BookCreateView

urlpatterns = [
    path('', index, name='index'),
    re_path(r'^books/$', BooksListView.as_view(), name='books'),
    re_path(r'^book/(?P<pk>\d+)$', BookDetailView.as_view(), name='book-detail'),
    re_path(r'^authors/$', AuthorsListView.as_view(), name='authors'),
    re_path(r'^author/(?P<pk>\d+)$', AuthorDetailView.as_view(), name='author-detail'),
    re_path(r'add_author/$', AuthorCreateView.as_view(), name='add_author'),
    re_path(r'add_book/$', BookCreateView.as_view(), name='add_book'),
]

locallibrary/locallibrary/urls.py
from django.contrib import admin
from django.urls import re_path, path, include


urlpatterns = [
    re_path(r'^admin/', admin.site.urls),
    path('catalog/', include('catalog.urls'))
]

locallibrary/catalog/models.py
from django.urls import reverse
from django.db import models
from datetime import date
from django.contrib.auth.models import User


class Genre(models.Model):
    name = models.CharField(max_length=200)

    def __str__(self):
        return self.name

    
class Language(models.Model):
    name = models.CharField(max_length=200)

    def __str__(self):
        return self.name


class Author(models.Model):
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    date_of_birth = models.DateField(null=True, blank=True)
    date_of_death = models.DateField(null=True, blank=True)

    class Meta:
        ordering = ['last_name', 'first_name']

    def __str__(self):
        return f"{self.last_name} {self.first_name}"

    def get_absolute_url(self):
        return reverse('author-detail', args=[str(self.id)])


class Book(models.Model):
    title = models.CharField(max_length=200)
    author = models.ForeignKey(Author, on_delete=models.CASCADE)
    summary = models.TextField()
    isbn = models.CharField(max_length=13, unique=True)
    genre = models.ManyToManyField(Genre)
    language = models.ForeignKey(Language, on_delete=models.CASCADE, null=True)

    def __str__(self):
        return self.title

    class Meta:
        ordering = ['title', 'author']

    def get_absolute_url(self):
        return reverse('book-detail', args=[str(self.id)])

    def display_genre(self):
        return ', '.join([genre.name for genre in self.genre.all()])



class BookInstance(models.Model):
    LOAN_STATUS = (
        ('On loan', 'On loan'),
        ('Available', 'Available'),
        ('Reserved', 'Reserved')
    )

    book = models.ForeignKey(Book, on_delete=models.CASCADE)
    due_back = models.DateField(null=True, blank=True)
    borrower = models.ForeignKey(User, on_delete=models.SET_NULL, 
                                null=True, blank=True)
    status = models.CharField(choices=LOAN_STATUS, max_length=10, 
                                default='Available')

    def __str__(self):
        return self.book.title

    class Meta:
        ordering = ['due_back']

    def _is_overdue(self):
        return bool(self.due_back and date.today())

locallibrary/catalog/views.py
from django.shortcuts import render
from .models import Author, Book, BookInstance, Genre
from django.views.generic import ListView, DetailView
from django.views.generic.edit import CreateView
from django.forms import ModelForm, DateInput, ModelMultipleChoiceField, CheckboxSelectMultiple
from django.forms.fields import DateField


def index(request):
    num_books = Book.objects.all().count()
    num_instances = BookInstance.objects.all().count()
    num_instances_available = BookInstance.objects.filter(status__exact="Available").count()
    num_authors = Author.objects.all().count()

    return render(request, 'index.html', 
                {
                'num_books': num_books,
                'num_instances': num_instances,
                'num_instances_available': num_instances_available,
                "num_authors": num_authors,
                }
    )


class BooksListView(ListView):
    model = Book
    context_object_name = 'my_book_list'
    template_name = 'books_list.html'


class BookDetailView(DetailView):
    model = Book
    template_name = 'book_detail.html'


class AuthorsListView(ListView):
    model = Author
    context_object_name = 'authors_list'
    template_name = 'authors_list.html'


class AuthorDetailView(DetailView):
    model = Author
    template_name = 'author_detail.html'


class AuthorCreateForm(ModelForm):
    date_of_birth = DateField(required=False, widget=DateInput(attrs={'type': 'date'}))
    date_of_death = DateField(required=False, widget=DateInput(attrs={'type': 'date'}))
    class Meta:
        model = Author
        fields = '__all__'


class AuthorCreateView(CreateView):
    model = Author
    template_name = 'add_author.html'
    form_class = AuthorCreateForm


class BookCreateForm(ModelForm):
    genre = ModelMultipleChoiceField(
        queryset=Genre.objects.all(), widget=CheckboxSelectMultiple()
    )
    class Meta:
        model = Book
        fields = ['title', 'author', 'summary', 'isbn', 'genre', 'language']


class BookCreateView(CreateView):
    model = Book
    template_name = 'add_book.html'
    form_class = BookCreateForm

locallibrary/catalog/templates/add_author.html
{% extends "base.html" %}

{% block content %}

<div>
    <div class="col">
        <form method="post" class="add-author-form">{% csrf_token %}
            {{ form.as_p }}
            <input type="submit" value="Save">
        </form>
    </div>
</div>

{% endblock %}

locallibrary/catalog/templates/add_book.html
{% extends "base.html" %}

{% block content %}

<div>
    <div class="col">
        <form method="post" class="add-book-form">{% csrf_token %}
            {{ form.as_p }}
            <input type="submit" value="Save">
        </form>
    </div>
</div>

{% endblock %}

locallibrary/catalog/templates/author_detail.html
{% extends "base.html" %}

{% block content %}
  <h1>Author: {{ author.first_name }} {{author.last_name}}</h1>
{% endblock %}

locallibrary/catalog/templates/authors_list.html
{% extends "base.html" %}

{% block content %}
    <h1>Authors List</h1>

    {% if authors_list %}
    <ul>

      {% for author in authors_list %}
      <li>
        <a href="{{ author.get_absolute_url }}">{{ author.first_name }}</a> ({{author.last_name}})
      </li>
      {% endfor %}

    </ul>
    {% else %}
      <p>There are no authors in the library.</p>
    {% endif %}
{% endblock %}

locallibrary/catalog/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>

  {% block title %}<title>Local Library</title>{% endblock %}
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

  <!-- Добавление дополнительного статического CSS файла -->
  {% load static %}
  <link rel="stylesheet" href="{% static 'css/styles.css' %}">
</head>

<body>

  <div class="container-fluid">

    <div class="row">
      <div class="col-sm-2">
      {% block sidebar %}
      <ul class="sidebar-nav">
          <li><a href="{% url 'index' %}">Home</a></li>
          <li><a href="{% url 'books' %}">All books</a></li>
          <li><a href="{% url 'authors' %}">All authors</a></li>
          <li><a href="{% url 'add_author' %}">Add author</a></li>
          <li><a href="{% url 'add_book' %}">Add book</a></li>
      </ul>
     {% endblock %}
      </div>
      <div class="col-sm-10 ">
      {% block content %}{% endblock %}
      </div>
    </div>

  </div>
</body>
</html>

locallibrary/catalog/templates/book_detail.html
{% extends "base.html" %}

{% block content %}
  <h1>Title: {{ book.title }}</h1>

  <p><strong>Author:</strong> <a href="">{{ book.author }}</a></p> <!-- author detail link not yet defined -->
  <p><strong>Summary:</strong> {{ book.summary }}</p>
  <p><strong>ISBN:</strong> {{ book.isbn }}</p>
  <p><strong>Language:</strong> {{ book.language }}</p>
  <p><strong>Genre:</strong> {% for genre in book.genre.all %} {{ genre }}{% if not forloop.last %}, {% endif %}{% endfor %}</p>

  <div style="margin-left:20px;margin-top:20px">
    <h4>Copies</h4>

    {% for copy in book.bookinstance_set.all %}
    <hr>
    <p class="{% if copy.status == 'a' %}text-success{% elif copy.status == 'd' %}text-danger{% else %}text-warning{% endif %}">{{ copy.get_status_display }}</p>
    {% if copy.status != 'a' %}<p><strong>Due to be returned:</strong> {{copy.due_back}}</p>{% endif %}
    <p><strong>Imprint:</strong> {{copy.imprint}}</p>
    <p class="text-muted"><strong>Id:</strong> {{copy.id}}</p>
    {% endfor %}
  </div>
{% endblock %}

locallibrary/catalog/templates/books_list.html
{% extends "base.html" %}

{% block content %}
    <h1>Book List</h1>

    {% if my_book_list %}
    <ul>

      {% for book in my_book_list %}
      <li>
        <a href="{{ book.get_absolute_url }}">{{ book.title }}</a> ({{book.author}})
      </li>
      {% endfor %}

    </ul>
    {% else %}
      <p>There are no books in the library.</p>
    {% endif %}
{% endblock %}

locallibrary/catalog/templates/index.html
{% extends "base.html" %}

{% block content %}
<h1>Local Library Home</h1>

  <p>Welcome to <em>LocalLibrary</em>, a very basic Django website developed as a tutorial example on the Mozilla Developer Network.</p>

<h2>Dynamic content</h2>

  <p>The library has the following record counts:</p>
  <ul>
    <li><strong>Books:</strong> {{ num_books }}</li>
    <li><strong>Copies:</strong> {{ num_instances }}</li>
    <li><strong>Copies available:</strong> {{ num_instances_available }}</li>
    <li><strong>Authors:</strong> {{ num_authors }}</li>
  </ul>

{% endblock %}